name: "RTSP To Text"
description: "RTSP To Text"
version: "0.0.2"
slug: "rtsp_to_text"
image: "ghcr.io/starsoccer/rtsp-to-text/{arch}"
init: false
homeassistant_api: true
realtime: true
arch:
  - aarch64
  - amd64
  - armv7
startup: before
environment:
  model_path: "/models"
  vosk_so_path: "/vosk_so"
options:
  port: 7877
  model_url: "https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip"
  listen_length: 15000
  rtsp_username: null
  rtsp_password: null
  rtsp_url: "rtsps://192.168.0.1:7441"
  addon_username: null
  addon_password: null
  RTSP_lookup:
    - device_name: null
      rtsp_id: null
  log_level: "info"
schema:
  port: port
  model_url: url
  listen_length: int(5000,60000)
  rtsp_username: str
  rtsp_password: password
  rtsp_url: url
  addon_username: str
  addon_password: password
  RTSP_lookup:
    - device_name: str
      rtsp_id: str
  log_level: list(fatal|error|warn|info|debug|trace)